apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dev-rctest
  namespace: argocd
spec:
  project: development
  source:
    helm:
      valueFiles:
      - values.yaml
      values: |
        environment: dev
        redis:
          size: 1024
          stateful:
            enabled: false
          replicas: 1
    repoURL: https://github.com/rahulchak/rc-helm-redis
    targetRevision: HEAD
    path: charts/redis-dds
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  revisionHistoryLimit: 5
